require('options')
require('plugins')
require('user.impatient')
require('user.telescope')
require('user.treesitter')
require('user.cmp')
require('user.keymaps')
require('user.lsp')
require('user.autopairs')
require('user.nvim-tree')
require('user.lualine')
--require('user.null-ls')

